### ISSUE TITLE
Reaction enumerators can be sped up with multiprocessing

### ISSUE THREAD

**Issue by mattmcdermott** [GENESIS-EFRC/reaction-network#101]
In previous versions of the reaction-network package, we had some support for parallelizing the reaction enumerating loop using Dask. 

We should be able to add back in support for multiprocessing now that the refactor of the package has started to come to a close.

**Comment by mattmcdermott** [comment]
Implemented simple support for this using Ray. Preliminary tests seem to be going well.

**Comment by mattmcdermott** [comment]
Added in PR #106. Could use some minor improvements, but overall working!

**Comment by Imhaenoo** [comment]
Hi, matt! 

I want to know how to speed up the reaction enumerator.

I'm currently running reaction enumerators with over 10000 entries on my desktop and HPC.
My guess is that both cases will take a significant amount of time.

Here's an image to illustrate what's going on in the run.

1. My desktop
![image](https://github.com/materialsproject/reaction-network/assets/97152267/4ba32c76-d34e-4e79-9942-861d7372363c)

2. HPC
![image](https://github.com/materialsproject/reaction-network/assets/97152267/95705169-df2e-4b73-b4c2-21bd316523be)


Is there any way to speed up the reaction enumeration even with a large number of entries ?  

Regards
Kim

**Comment by mattmcdermott** [comment]
Hi @Imhaenoo,

That is a very big system. The largest system I've ever enumerated was ~2500 entries, and I used 4 powerful HPC nodes with a total of 1024 CPUs. I think the `BasicEnumerator` only took a few hours on this configuration, so a few thousand entries is do-able. Because the code has been parallelized, it should scale if you throw more compute at it. So you could try re-running this, but I would recommend no less than a thousand CPUs for your system. You may also run into some memory constraints (I have sometimes run out of memory for very large systems).

If possible, it would be best just to filter your entries down to a smaller stability threshold (via `GibbsEntrySet.filter_by_stability`). What are you currently using?

**Comment by Imhaenoo** [comment]
@mattmcdermott, thanks for the quick response! 

I first realized from your response that `BasicEnumerator` for large systems require quite a bit more CPU power than I thought.
(This is because I've only ever used it with 100 entries or less.) Hence I agree that it is reasonable to use `GibbsEntrySet.filter_by_stability` to reduce the number of entries and I am also currently using 0.1 eV/atom.

However, the network reaction paper (Nat. Commun., 12, 3097, 2021) states that 21,546 entries were used at a section of the MgMo3(PO4)3O design. I noticed this and hence thought that my entries of 17,000 would be possible.

![image](https://github.com/materialsproject/reaction-network/assets/97152267/836e2668-082a-4bf7-b906-972d1e2f34f9)

Did you enumerate the reactions using a significant amount of CPU and long hours of computing?

Regards

**Comment by mattmcdermott** [comment]
Oh I see -- I missed that you had specified a target in your enumerator. 

If you are just enumerating to a particular target, you might be able to do this with your 17K entries. The problem instead might have to do with your HPC configuration. If you are running on multiple HPC nodes, you need to tell Ray which nodes to use by creating your own cluster. I have modified the scripts here to do this on my computing resources:

https://github.com/NERSC/slurm-ray-cluster

Hope this helps.

**Comment by Imhaenoo** [comment]
Thanks for introducing such a helpful tool, Ray. 
I am enumerating the reactions via the slurm-ray-cluster.sbatch you provided.

I have one more question about the CPU load rate.

When you ran Reaction Enumerator on HPC, was the CPU load 100% utilized?
In my case, when I run it on 2 HPCs with 32 cores/node, the CPU load is quite low (~1%).

> HPC
![image](https://github.com/materialsproject/reaction-network/assets/97152267/2cc03062-02e1-4c5e-a87a-164dd5cd8e3e)

Is this considered working? 

Regards

**Comment by mattmcdermott** [comment]
You should be getting more CPU utilization than 1%, but it will likely be less than 100%. I think you can expect somewhere in the 60-90% range.

It doesn't seem like Ray is properly configured on your HPC right now. If you look at the printed output, it says that an existing Ray cluster was not found. I would check that the Ray cluster initialization script runs  correctly at the beginning of the job. It may take some troubleshooting of the script, but once you get it working I think it should be reliable for you -- I have been running this way for over a year now. Sorry this is not detailed troubleshooting information since it is somewhat system dependent. Hope this helps!

**Comment by Imhaenoo** [comment]
I realized that the 1% CPU load meant that something was wrong.

I'll try to modify the jobscript so that Ray is well configured for my HPC.  

Thank you for your thoughtful and quick response! 

Have a nice day!
