### ISSUE TITLE
Oversight: `calculate_e_above_hulls` function in `GibbsEntrySet` only works when entries cover whole phase diagram

### ISSUE THREAD

**Issue by mattmcdermott** [GENESIS-EFRC/reaction-network#103]
This function doesn't work in situations where you want to initialize a GibbsEntrySet from a list of entries that doesn't span the entire phase space. 

Perhaps this should have a restriction / logic to check for this?

**Comment by mattmcdermott** [comment]
This matters especially for `PathwaySolver`

**Comment by mattmcdermott** [comment]
@zhugeyicixin FYI -- this is the bug that you encountered. I need to focus on some other things first but will address as soon as possible!

**Comment by zhugeyicixin** [comment]
> @zhugeyicixin FYI -- this is the bug that you encountered. I need to focus on some other things first but will address as soon as possible!

Thanks, Matt!

**Comment by mattmcdermott** [comment]
Should be fixed with PR #106
