### ISSUE TITLE
Setup Issue (setuptools-scm was unable to detect version for)

### ISSUE THREAD

**Issue by 103-5** [GENESIS-EFRC/reaction-network#105]
I follow the instruction in the README and all steps are completed except
`pip install -e .` , it results in lots of errors (see below).
It seems that setup.py needs to be modified due to 
> LookupError: setuptools-scm was unable to detect version for /root.

I've tried the solution (as following) in https://github.com/pypa/setuptools_scm/issues/536 but it doesn't work
`use_scm_version={"root": "..",  
                       "relative_to": __file__,  
                       "version_scheme": "no-guess-dev"},` 

Here is the errors:
> (gt) root@iZ8vb98m8jfeytc3k1bao2Z:~/reaction-network-main# pip install -e.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Obtaining file:///root/reaction-network-main
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  ?python setup.py egg_info did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [32 lines of output]
      /root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/dist.py:744: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        warnings.warn(
      /root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_requires'
        warnings.warn(msg)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/root/reaction-network-main/setup.py", line 12, in <module>
          setup(
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in setup
          return distutils.core.setup(**attrs)
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/dist.py", line 462, in __init__
          _Distribution.__init__(
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/dist.py", line 868, in finalize_options
          ep(self)
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools/dist.py", line 889, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools_scm/integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/root/anaconda3/envs/gt/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /root.
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
?Encountered error while generating package metadata.
\u2570\u2500> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mattmcdermott** [comment]
Hi @103-5 , thanks for raising an issue! I am not as familiar with setup-tools, but it might be a problem with how you've downloaded the code. Are you downloading via a ZIP file or using Git to clone the repo to your machine?

**Comment by 103-5** [comment]
> Hi @103-5 , thanks for raising an issue! I am not an expert with setup-tools, but it might be a problem with how you've downloaded the code. Are you downloading via a ZIP file or using Git to clone the repo to your machine?

**Comment by 103-5** [comment]
Hi @mattmcdermott, thanks for your attention. I downloaded the ZIP file and unzipped it to the root folder.
![image](https://user-images.githubusercontent.com/17380266/160547786-ff25c844-7863-483f-90ca-3aec116386d1.png)

**Comment by mattmcdermott** [comment]
The good news is I was able to recreate your error by downloading the ZIP folder; I hadn't noticed this problem because I always install via `git clone https://github.com/GENESIS-EFRC/reaction-network.git`.

Since this seems more like a pip metadata issue, I would suggest one of these two options:

1) install a non-editable version of the code by doing `pip install reaction-network` (this will download and install from PyPI)
2) Install an editable version of the code by using the git clone command above and then the usual `pip install -e .` from within the directory.

If you are not doing any development on the code option 1 should be easy -- just make sure if you're running stuff with networks to install the additional `graph-tool` dependency as is specified in the README instructions.

**Comment by 103-5** [comment]
> The good news is I was able to recreate your error by downloading the ZIP folder; I hadn't noticed this problem because I always install via `git clone https://github.com/GENESIS-EFRC/reaction-network.git`.
> 
> Since this seems more like a pip metadata issue, I would suggest one of these two options:
> 
> 1. install a non-editable version of the code by doing `pip install reaction-network` (this will download and install from PyPI)
> 2. Install an editable version of the code by using the git clone command above and then the usual `pip install -e .` from within the directory.
> 
> If you are not doing any development on the code, then Option 1 should be very straightforward -- just make sure if you're running stuff with networks to install the additional `graph-tool` dependency as is specified in the README instructions.

Thanks for your help. Both of these two options works! The downloaded zip lacks .git folder compared to git clone one, and it might be the reason why the pip metadata issue exists.

**Comment by mattmcdermott** [comment]
That's great to hear you got it working! I'll make a note in the README instructions in a future PR.
