### ISSUE TITLE
Expand the entry_set for new molecules

### ISSUE THREAD

**Issue by sli259** [GENESIS-EFRC/reaction-network#162]
Hi, I am trying to use the network for a specific reaction. What if the MP database doesn't have the reactant or product for my reaction? Can I manually add entries to the entry_set? For example, I have a reactant acetonitrile (H3C2N), but this is not included in the MP set. 
Can you let me know how to expand the entry_set in this case?

Thanks!

**Comment by mattmcdermott** [comment]
Hi @sli259, sorry for the delay in responding!

Yes, you should be able to add entries of arbitrary formulas. Once you have a `GibbsEntrySet` created, you should be able to call the function `GibbsEntrySet.get_interpolated_entry()` and supply your desired formula (e.g., `"H3C2N"`) as the argument. 

This will create an `InterpolatedEntry` object, which is a "fake" entry with the composition specified and formation energy that puts it just on the hull.

**Comment by mattmcdermott** [comment]
Closing this issue. Feel free to reopen @sli259 if you have further questions. Thanks!
