### ISSUE TITLE
[BUG] file not found error after pip install

### ISSUE THREAD

**Issue by CLRom** [GENESIS-EFRC/reaction-network#217]
pip install runs fine, but when I try to load any of the packages into a jupyter notebook, I get a file-not-found error.
e.g., from rxn_network.enumerators.basic import BasicEnumerator
leads to
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/envs/pmg/lib/python3.10/site-packages/rxn_network/data/barin/compounds.json.gz'

The "/opt/anaconda3/envs/pmg/lib/python3.10/site-packages/rxn_network/data" folder is missing files and folders that are present in the /src/rxn_network folder on github. 

<img width="552" alt="Screen Shot 2023-01-29 at 8 38 33 PM" src="https://user-images.githubusercontent.com/44926240/215382502-b6a157d1-4e43-4938-b209-cef9beca5904.png">

Not sure if this issue is on my end, or if the "pip install reaction-network" somehow goofed. Regardless, reaction-network is awesome Matt! Look forward to using it more soon

**Comment by mattmcdermott** [comment]
Hi Chris, thank you for catching this bug! @R1j1t found this bug as well and was able to address it before I got around to figuring it out. Long story short -- the experimental data files used by `GibbsEntrySet` were getting deleted when the package was being built for PyPI. 

It should be fixed now. I'll get a new version on PyPI tomorrow. 

In the meantime, if you want to use the package right away, I would suggest installing it from the source code (i.e., clone the repository from Github, change to the directory where you downloaded the code, and then run `pip install -e .` (make sure to get the dot in there)

**Comment by mattmcdermott** [comment]
Fixed with #218

**Comment by mattmcdermott** [comment]
New version 7.0.1 on PyPI. let me know if it works?

**Comment by R1j1t** [comment]
Hi @mattmcdermott all the data files were packaged in the new release!
